// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/aarondl/oa3/support"
)

type PrimitivesStr string

const (
	PrimitivesStrHello = PrimitivesStr("hello")
)

// validateSchema validates the object and returns
// errors that can be returned to the user.
func (o PrimitivesStr) validateSchema() support.Errors {
	var ctx []string
	var ers []error
	var errs support.Errors
	_, _, _ = ctx, ers, errs

	ers = nil
	if err := support.ValidateMaxLength(o, 5); err != nil {
		ers = append(ers, err)
	}
	if err := support.ValidateMinLength(o, 5); err != nil {
		ers = append(ers, err)
	}
	if err := support.ValidateEnum(o, []string{"hello"}); err != nil {
		ers = append(ers, err)
	}

	return errs
}
