// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/volatiletech/null"
)

// Checks to see that all Go primitives work
type Primitives struct {
	Bool        bool         `json:"bool"`
	BoolNull    null.Bool    `json:"bool_null"`
	Float       float64      `json:"float"`
	Float32     float32      `json:"float32"`
	Float32Null null.Float32 `json:"float32_null"`
	Float64     float64      `json:"float64"`
	Float64Null null.Float64 `json:"float64_null"`
	FloatNull   null.Float64 `json:"float_null"`
	// Normal int
	Int       int         `json:"int"`
	Int32     int32       `json:"int32"`
	Int32Null null.Int32  `json:"int32_null"`
	Int64     int64       `json:"int64"`
	Int64Null null.Int64  `json:"int64_null"`
	IntNull   null.Int    `json:"int_null"`
	Str       string      `json:"str"`
	StrNull   null.String `json:"str_null"`
}
