// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"fmt"
	"strings"

	"github.com/aarondl/oa3/support"
)

// Embedded object in an array
type ArrayEmbedded []ArrayEmbeddedItem

// This object is embedded in an array
type ArrayEmbeddedItem struct {
	Prop string `json:"prop"`
}

// ValidateSchemaArrayEmbeddedItem validates the object and returns
// errors that can be returned to the user.
func (o ArrayEmbeddedItem) ValidateSchemaArrayEmbeddedItem() support.Errors {
	var ctx []string
	var ers []error
	var errs support.Errors
	_, _, _ = ctx, ers, errs

	errs = support.AddErrs(errs, "", ers...)

	return errs
}

// ValidateSchemaArrayEmbedded validates the object and returns
// errors that can be returned to the user.
func (o ArrayEmbedded) ValidateSchemaArrayEmbedded() support.Errors {
	var ctx []string
	var ers []error
	var errs support.Errors
	_, _, _ = ctx, ers, errs

	for i, o := range o {
		var ers []error
		ctx = append(ctx, fmt.Sprintf("[%d]", i))

		errs = support.AddErrs(errs, strings.Join(ctx, "."), ers...)
		ctx = ctx[:len(ctx)-1]
	}

	errs = support.AddErrs(errs, "", ers...)

	return errs
}
