// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/aarondl/oa3/support"
)

// Recursive definition of an array
type ArrayRecursive [][][]string

// ValidateSchemaArrayRecursive validates the object and returns
// errors that can be returned to the user.
func (o ArrayRecursive) ValidateSchemaArrayRecursive() support.Errors {
	var errs support.Errors

	if err := support.MaxItems(o, 10); err != nil {
		ers = append(ers, err)
	}

	if err := support.MinItems(o, 2); err != nil {
		ers = append(ers, err)
	}
	for _, v := range o {
		if err := support.MaxItems(oo, 8); err != nil {
			ers = append(ers, err)
		}

		if err := support.MinItems(oo, 5); err != nil {
			ers = append(ers, err)
		}
		for _, v := range oo {
			if err := support.MaxItems(ooo, 15); err != nil {
				ers = append(ers, err)
			}

			if err := support.MinItems(ooo, 12); err != nil {
				ers = append(ers, err)
			}
			for _, v := range ooo {
				ers = nil
			}

		}

	}

	return errs
}
