// === schema_array.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type Array []string

// === schema_array_embedded.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type ArrayEmbedded []ArrayEmbeddedItem

type ArrayEmbeddedItem struct {
    Prop string
}


// === schema_array_recursive.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type ArrayRecursive [][][]string

// === schema_arrays.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type Arrays struct {
    Array []string
}

// === schema_map.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type Map map[string][]string

// === schema_map_embedded.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type MapEmbedded map[string]MapEmbeddedItem

type MapEmbeddedItem struct {
    Prop string
}


// === schema_map_recursive.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type MapRecursive map[string]map[string]map[string]string

// === schema_primitives.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	github.com/volatiletech/null
)

type Primitives struct {
    Bool bool
    BoolNull null.Bool
    Float float64
    Float32 float32
    Float32Null null.Float32
    Float64 float64
    Float64Null null.Float64
    FloatNull null.Float64
    // Normal int
    Int int
    Int32 int32
    Int32Null null.Int32
    Int64 int64
    Int64Null null.Int64
    IntNull null.Int
    Str string
    StrNull null.String
}

// === schema_ref.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type Ref struct {
    RefNormal RefTarget
    RefNull RefTargetNullable
}

// === schema_ref_target.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type RefTarget struct {
    Property string
}

// === schema_ref_target_nullable.go
// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type RefTargetNullable struct {
    Property string
}

