// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/aarondl/oa3/support"
)

// An example of an object that can be exactly one of 3 things
type AnyOf interface {
	AnyOfTypeCheck()
}

type AnyOfIntf interface {
	AnyOfTypeCheck()
}

// ValidateSchemaAnyOf validates the object and returns
// errors that can be returned to the user.
func (o AnyOf) ValidateSchemaAnyOf() support.Errors {
	var errs support.Errors

	return errs
}
