// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

// Enum type
type Enum string

const (
	EnumOne   Enum = "one"
	EnumTwo   Enum = "two"
	EnumThree Enum = "three"
)
