// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/aarondl/opt/omit"
)

type EntityWithTag struct {
	WithDash       omit.Val[string] `json:"with-dash,omitempty"`
	WithUnderscore omit.Val[string] `json:"with_underscore,omitempty"`
}
