// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"time"

	"github.com/aarondl/chrono"
	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
)

// Checks to see that all Go primitives work
type Primitives struct {
	Bool         bool                        `json:"bool"`
	BoolNull     null.Val[bool]              `json:"bool_null"`
	DateNull     null.Val[chrono.Date]       `json:"date_null"`
	DateVal      chrono.Date                 `json:"date_val"`
	DatetimeNull null.Val[chrono.DateTime]   `json:"datetime_null"`
	DatetimeVal  chrono.DateTime             `json:"datetime_val"`
	DurationNull omitnull.Val[time.Duration] `json:"duration_null,omitempty"`
	DurationVal  omit.Val[time.Duration]     `json:"duration_val,omitempty"`
	Float        float64                     `json:"float"`
	Float32      float32                     `json:"float32"`
	Float32Null  null.Val[float32]           `json:"float32_null"`
	Float64      float64                     `json:"float64"`
	Float64Null  null.Val[float64]           `json:"float64_null"`
	FloatNull    null.Val[float64]           `json:"float_null"`
	// Normal int
	Int       int                   `json:"int"`
	Int32     int32                 `json:"int32"`
	Int32Null null.Val[int32]       `json:"int32_null"`
	Int64     int64                 `json:"int64"`
	Int64Null null.Val[int64]       `json:"int64_null"`
	IntNull   null.Val[int]         `json:"int_null"`
	Str       PrimitivesStr         `json:"str"`
	StrFormat string                `json:"str_format"`
	StrNull   PrimitivesStrNull     `json:"str_null"`
	TimeNull  null.Val[chrono.Time] `json:"time_null"`
	TimeVal   chrono.Time           `json:"time_val"`
}

type PrimitivesStr string

const (
	PrimitivesStrHello = PrimitivesStr("hello")
)

type PrimitivesStrNull string

var (
	PrimitivesStrNullHello = PrimitivesStrNull("hello")
)
