// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

// References to other objects
type Ref struct {
	RefNormal RefTarget         `json:"ref_normal"`
	RefNull   RefTargetNullable `json:"ref_null,omitempty"`
}
