// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

// Embedded array objects break
type MapBug struct {
	Yap []MapBugYapItem `json:"yap,omitempty"`
}
