// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

import (
	"github.com/aarondl/opt/omit"
)

type EntityWithDash struct {
	WithDash              omit.Val[string] `json:"with-dash,omitempty"`
	WithDashAndUnderscore omit.Val[string] `json:"with-dash_and_underscore,omitempty"`
	WithUnderscore        omit.Val[string] `json:"with_underscore,omitempty"`
}
