// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

// Map types with an embedded object
type MapEmbedded map[string]MapEmbeddedItem
