// Code generated by oa3 (https://github.com/aarondl/oa3). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.
package oa3gen

type GetUserGetArrayEnumFlatParam []GetUserGetArrayEnumFlatParamItem

type GetUserGetArrayEnumFlatParamItem string

const (
	GetUserGetArrayEnumFlatParamItemA = GetUserGetArrayEnumFlatParamItem("a")
	GetUserGetArrayEnumFlatParamItemB = GetUserGetArrayEnumFlatParamItem("b")
)
